/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AppInstitutionsRouteImport } from './routes/_app/institutions'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppGrantsRouteImport } from './routes/_app/grants'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppConfigurationIndexRouteImport } from './routes/_app/configuration/index'
import { Route as AuthOpenidCallbackRouteImport } from './routes/auth/openid/callback'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users.$userId'
import { Route as AppInstitutionsTenantIdRouteImport } from './routes/_app/institutions.$tenantId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutionsRoute = AppInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantsRoute = AppGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigurationIndexRoute = AppConfigurationIndexRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => AppRoute,
} as any)
const AuthOpenidCallbackRoute = AuthOpenidCallbackRouteImport.update({
  id: '/auth/openid/callback',
  path: '/auth/openid/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppInstitutionsTenantIdRoute = AppInstitutionsTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => AppInstitutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/grants': typeof AppGrantsRoute
  '/help': typeof AppHelpRoute
  '/institutions': typeof AppInstitutionsRouteWithChildren
  '/usage': typeof AppUsageRoute
  '/users': typeof AppUsersRouteWithChildren
  '/institutions/$tenantId': typeof AppInstitutionsTenantIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/auth/openid/callback': typeof AuthOpenidCallbackRoute
  '/configuration/': typeof AppConfigurationIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/grants': typeof AppGrantsRoute
  '/help': typeof AppHelpRoute
  '/institutions': typeof AppInstitutionsRouteWithChildren
  '/usage': typeof AppUsageRoute
  '/users': typeof AppUsersRouteWithChildren
  '/': typeof AppIndexRoute
  '/institutions/$tenantId': typeof AppInstitutionsTenantIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/auth/openid/callback': typeof AuthOpenidCallbackRoute
  '/configuration': typeof AppConfigurationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/grants': typeof AppGrantsRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/institutions': typeof AppInstitutionsRouteWithChildren
  '/_app/usage': typeof AppUsageRoute
  '/_app/users': typeof AppUsersRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/institutions/$tenantId': typeof AppInstitutionsTenantIdRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/auth/openid/callback': typeof AuthOpenidCallbackRoute
  '/_app/configuration/': typeof AppConfigurationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/grants'
    | '/help'
    | '/institutions'
    | '/usage'
    | '/users'
    | '/institutions/$tenantId'
    | '/users/$userId'
    | '/auth/openid/callback'
    | '/configuration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/access'
    | '/grants'
    | '/help'
    | '/institutions'
    | '/usage'
    | '/users'
    | '/'
    | '/institutions/$tenantId'
    | '/users/$userId'
    | '/auth/openid/callback'
    | '/configuration'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/access'
    | '/_app/grants'
    | '/_app/help'
    | '/_app/institutions'
    | '/_app/usage'
    | '/_app/users'
    | '/_app/'
    | '/_app/institutions/$tenantId'
    | '/_app/users/$userId'
    | '/auth/openid/callback'
    | '/_app/configuration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthOpenidCallbackRoute: typeof AuthOpenidCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institutions': {
      id: '/_app/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof AppInstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grants': {
      id: '/_app/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof AppGrantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuration/': {
      id: '/_app/configuration/'
      path: '/configuration'
      fullPath: '/configuration/'
      preLoaderRoute: typeof AppConfigurationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/openid/callback': {
      id: '/auth/openid/callback'
      path: '/auth/openid/callback'
      fullPath: '/auth/openid/callback'
      preLoaderRoute: typeof AuthOpenidCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/_app/institutions/$tenantId': {
      id: '/_app/institutions/$tenantId'
      path: '/$tenantId'
      fullPath: '/institutions/$tenantId'
      preLoaderRoute: typeof AppInstitutionsTenantIdRouteImport
      parentRoute: typeof AppInstitutionsRoute
    }
  }
}

interface AppInstitutionsRouteChildren {
  AppInstitutionsTenantIdRoute: typeof AppInstitutionsTenantIdRoute
}

const AppInstitutionsRouteChildren: AppInstitutionsRouteChildren = {
  AppInstitutionsTenantIdRoute: AppInstitutionsTenantIdRoute,
}

const AppInstitutionsRouteWithChildren = AppInstitutionsRoute._addFileChildren(
  AppInstitutionsRouteChildren,
)

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppGrantsRoute: typeof AppGrantsRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInstitutionsRoute: typeof AppInstitutionsRouteWithChildren
  AppUsageRoute: typeof AppUsageRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppConfigurationIndexRoute: typeof AppConfigurationIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppGrantsRoute: AppGrantsRoute,
  AppHelpRoute: AppHelpRoute,
  AppInstitutionsRoute: AppInstitutionsRouteWithChildren,
  AppUsageRoute: AppUsageRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppConfigurationIndexRoute: AppConfigurationIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthOpenidCallbackRoute: AuthOpenidCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
